<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class AcademicUnitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // get timestamp creation dates
        $now = Carbon::now();

        // database inserts
        DB::table('public.academic_units')->insert([
            ['key' => '720', '_key' => '', 'name' => 'ARTEAC. FÁBRICA DE TALENTOS, S.C.', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '314', '_key' => 'BI', 'name' => 'BACHILLERATO "5 DE MAYO"', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '29', '_key' => '', 'name' => 'BACHILLERATOS BUAP', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '710', '_key' => '', 'name' => 'CENTRO DE ESTUDIOS LAS AMÉRICAS', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '705', '_key' => '', 'name' => 'CENTRO DE ESTUDIOS UNIVERSITARIOS DEL INSTITUTO CRISTÓBAL COLÓN', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '712', '_key' => '', 'name' => 'CENTRO DE INVESTIGACIÓN Y ESTUDIOS SUPERIORES EN ESTOMATOLOGÍA Y SALUD, S.C.', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '706', '_key' => '', 'name' => 'CENTRO DE INVESTIGACIÓN Y ESTUDIOS UNIVERSITARIOS PARA EL DESARROLLO', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '711', '_key' => '', 'name' => 'CENTRO EDUCATIVO DE LA REGIÓN DE TEXMELUCAN', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '701', '_key' => '', 'name' => 'COLEGIO UNIVERSITARIO DE PUEBLA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '704', '_key' => '', 'name' => 'COLEGIO UNIVERSITARIO TOLTECA DE MÉXICO, A.C.', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '601', '_key' => 'CC', 'name' => 'COMPLEJO REGIONAL CENTRO', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '602', '_key' => 'CX', 'name' => 'COMPLEJO REGIONAL MIXTECA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '603', '_key' => 'CR', 'name' => 'COMPLEJO REGIONAL NORORIENTAL', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '604', '_key' => 'CN', 'name' => 'COMPLEJO REGIONAL NORTE', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '605', '_key' => 'CU', 'name' => 'COMPLEJO REGIONAL SUR', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '382', '_key' => 'AP', 'name' => 'ESCUELA DE ARTES PLÁSTICAS Y AUDIOVISUALES', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '707', '_key' => '', 'name' => 'ESCUELA DE JURISPRUDENCIA Y HUMANIDADES', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '306', '_key' => '306', 'name' => 'ESCUELA PREPARATORIA "2 DE OCTUBRE"', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '307', '_key' => '307', 'name' => 'ESCUELA PREPARATORIA "ALFONSO CALDERÓN MORENO"', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '309', '_key' => '309', 'name' => 'ESCUELA PREPARATORIA "EMILIANO ZAPATA"', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '312', '_key' => '312', 'name' => 'ESCUELA PREPARATORIA "GENERAL LÁZARO CÁRDENAS DEL RÍO"', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '308', '_key' => '308', 'name' => 'ESCUELA PREPARATORIA "LIC. BENITO JUÁREZ GARCÍA"', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '310', '_key' => '310', 'name' => 'ESCUELA PREPARATORIA REGIONAL "ENRIQUE CABRERA BARROSO"', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '313', '_key' => '313', 'name' => 'ESCUELA PREPARATORIA REGIONAL "SIMÓN BOLÍVAR"', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '311', '_key' => '311', 'name' => 'ESCUELA PREPARATORIA URBANA "ENRIQUE CABRERA BARROSO"', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '326', '_key' => 'AD', 'name' => 'FACULTAD DE ADMINISTRACIÓN', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '351', '_key' => 'AR', 'name' => 'FACULTAD DE ARQUITECTURA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '508', '_key' => 'MU', 'name' => 'FACULTAD DE ARTES', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '352', '_key' => 'IA', 'name' => 'FACULTAD DE CIENCIAS AGRÍCOLAS Y PECUARIAS', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '341', '_key' => 'BI', 'name' => 'FACULTAD DE CIENCIAS BIOLÓGICAS', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '348', '_key' => 'CO', 'name' => 'FACULTAD DE CIENCIAS DE LA COMPUTACIÓN', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '375', '_key' => 'CM', 'name' => 'FACULTAD DE CIENCIAS DE LA COMUNICACIÓN', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '349', '_key' => 'EE', 'name' => 'FACULTAD DE CIENCIAS DE LA ELECTRÓNICA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '342', '_key' => 'FM', 'name' => 'FACULTAD DE CIENCIAS FÍSICO MATEMÁTICAS', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '328', '_key' => 'FP', 'name' => 'FACULTAD DE CIENCIAS POLÍTICAS Y SOCIALES', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '346', '_key' => 'CQ', 'name' => 'FACULTAD DE CIENCIAS QUÍMICAS', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '327', '_key' => 'CP', 'name' => 'FACULTAD DE CONTADURÍA PÚBLICA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '374', '_key' => 'CF', 'name' => 'FACULTAD DE CULTURA FÍSICA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '331', '_key' => 'FD', 'name' => 'FACULTAD DE DERECHO', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '333', '_key' => 'EC', 'name' => 'FACULTAD DE ECONOMÍA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '363', '_key' => 'EN', 'name' => 'FACULTAD DE ENFERMERÍA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '362', '_key' => 'ET', 'name' => 'FACULTAD DE ESTOMATOLOGÍA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '371', '_key' => 'FI', 'name' => 'FACULTAD DE FILOSOFÍA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '353', '_key' => 'IC', 'name' => 'FACULTAD DE INGENIERÍA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '354', '_key' => 'IQ', 'name' => 'FACULTAD DE INGENIERÍA QUÍMICA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '372', '_key' => 'EL', 'name' => 'FACULTAD DE LENGUAS', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '361', '_key' => 'ME', 'name' => 'FACULTAD DE MEDICINA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '381', '_key' => 'MV', 'name' => 'FACULTAD DE MEDICINA VETERINARIA Y ZOOTECNIA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '373', '_key' => 'PS', 'name' => 'FACULTAD DE PSICOLOGÍA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '713', '_key' => '', 'name' => 'INSTITUTO ANGELOPOLITANO DE ESTUDIOS UNIVERSITARIOS', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '402', '_key' => '', 'name' => 'INSTITUTO DE CIENCIAS', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '420', '_key' => '', 'name' => 'INSTITUTO DE CIENCIAS DE GOBIERNO Y DESARROLLO ESTRATÉGICO', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '703', '_key' => '', 'name' => 'INSTITUTO DE CIENCIAS JURÍDICAS DE PUEBLA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '403', '_key' => '', 'name' => 'INSTITUTO DE CIENCIAS SOCIALES Y HUMANIDADES "ALFONSO VÉLEZ PLIEGO"', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '708', '_key' => '', 'name' => 'INSTITUTO DE ESTUDIOS AVANZADOS SIGLO XXI, A.C.', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '709', '_key' => '', 'name' => 'INSTITUTO DE ESTUDIOS SUPERIORES EN ARQUITECTURA Y DISEÑO, A.C.', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '404', '_key' => '', 'name' => 'INSTITUTO DE FÍSICA "ING. LUIS RIVERA TERRAZAS"', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '405', '_key' => '', 'name' => 'INSTITUTO DE FISIOLOGÍA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '702', '_key' => '', 'name' => 'INSTITUTO POBLANO DE ESTUDIOS SUPERIORES, A.C.', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '714', '_key' => '', 'name' => 'INSTITUTO UNIVERSITARIO CENTRO OESTE DE PUEBLA', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '715', '_key' => '', 'name' => 'INSTITUTO UNIVERSITARIO FRANCISCO UGALDE', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '315', '_key' => '', 'name' => 'PREPARATORIA SECC. SAN MARTIN TEX', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '28', '_key' => '', 'name' => 'PREPARATORIAS BUAP', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '30', '_key' => '', 'name' => 'TÉCNICO MEDIO SUPERIOR BUAP', 'type' => 'academic', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '112', '_key' => '', 'name' => 'ABOGADO GENERAL', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '103', '_key' => '', 'name' => 'ARCHIVO HISTÓRICO REGIONAL UNIVERSITARIO', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '391', '_key' => '', 'name' => 'BIBLIOTECA ÁREA DE LA SALUD', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '392', '_key' => '', 'name' => 'BIBLIOTECA CENTRAL', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '387', '_key' => '', 'name' => 'BIBLIOTECA HISTÓRICA JOSE MARIA LAFRAGUA', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '410', '_key' => '', 'name' => 'BIOTERIO CLAUDE BERNARD', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '219', '_key' => '', 'name' => 'BUFETE JURÍDICO UNIVERSITARIO GRATUITO', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '220', '_key' => '', 'name' => 'CASA DEL JUBILADO', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '223', '_key' => '', 'name' => 'CENTRO DE APOYO EMOCIONAL Y TERAPIA OCUPACIONAL (CAETO)', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '422', '_key' => '', 'name' => 'CENTRO DE DETECCIÓN BIOMOLECULAR', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '137', '_key' => '', 'name' => 'CENTRO DE INNOVACIÓN Y DISEÑO DIGITAL', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '133', '_key' => '', 'name' => 'CENTRO UNIVERSITARIO DE PARTICIPACIÓN SOCIAL', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '409', '_key' => '', 'name' => 'CENTRO UNIVERSITARIO DE PREVENCIÓN DE DESASTRES REGIONALES', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '411', '_key' => '', 'name' => 'CENTRO UNIVERSITARIO DE VINCULACIÓN', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '806', '_key' => '', 'name' => 'CÍRCULO INFANTIL', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '225', '_key' => '', 'name' => 'CIUDAD UNIVERSITARIA 2', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '211', '_key' => '', 'name' => 'COMISIONADOS ADMINISTRATIVOS', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '212', '_key' => '', 'name' => 'COMISIONADOS DOCENTES', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '511', '_key' => '', 'name' => 'COMPLEJO CULTURAL UNIVERSITARIO', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '111', '_key' => '', 'name' => 'CONTRALORÍA GENERAL', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '118', '_key' => '', 'name' => 'COORDINACIÓN DE GABINETE', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '119', '_key' => '', 'name' => 'COORDINACIÓN DE PROYECTOS', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '144', '_key' => '', 'name' => 'COORDINACIÓN DEL ECOCAMPUS VALSEQUILLO', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '131', '_key' => '', 'name' => 'COORDINACIÓN GENERAL ADMINISTRATIVA', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '143', '_key' => '', 'name' => 'COORDINACIÓN GENERAL DE ATENCIÓN A LOS UNIVERSITARIOS', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '816', '_key' => '', 'name' => 'COORDINACIÓN GENERAL DE DESARROLLO SUSTENTABLE', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '115', '_key' => '', 'name' => 'DEFENSORÍA DE LOS DERECHOS UNIVERSITARIOS', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '802', '_key' => '', 'name' => 'DEPARTAMENTO DE ADQUISICIONES, PROVEEDURÍA E INVENTARIOS', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '138', '_key' => '', 'name' => 'DIRECCIÓN DE ACOMPAÑAMIENTO UNIVERSITARIO', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '206', '_key' => '', 'name' => 'DIRECCIÓN DE ADMINISTRACIÓN ESCOLAR', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '213', '_key' => '', 'name' => 'DIRECCIÓN DE APOYO Y SEGURIDAD UNIVERSITARIA', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '121', '_key' => '', 'name' => 'DIRECCIÓN DE COMUNICACIÓN', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '804', '_key' => '', 'name' => 'DIRECCIÓN DE CONTABILIDAD GENERAL', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '600', '_key' => '', 'name' => 'DIRECCIÓN DE DEPORTE Y CULTURA FÍSICA', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '610', '_key' => '', 'name' => 'DIRECCIÓN DE DEPORTES DE COMBATE', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '317', '_key' => '', 'name' => 'DIRECCIÓN DE EDUCACIÓN MEDIA SUPERIOR', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '510', '_key' => '', 'name' => 'DIRECCIÓN DE EDUCACIÓN SUPERIOR', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '142', '_key' => '', 'name' => 'DIRECCIÓN DE GESTIÓN', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '123', '_key' => '', 'name' => 'DIRECCIÓN DE INFRAESTRUCTURA EDUCATIVA', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '408', '_key' => '', 'name' => 'DIRECCIÓN DE INNOVACIÓN Y TRANSFERENCIA DEL CONOCIMIENTO', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '803', '_key' => '', 'name' => 'DIRECCIÓN DE RECURSOS HUMANOS', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '214', '_key' => '', 'name' => 'DIRECCIÓN DE SERVICIO SOCIAL', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '516', '_key' => '', 'name' => 'DIRECCIÓN DE SERVICIOS AL ESTUDIANTE', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '805', '_key' => '', 'name' => 'DIRECCIÓN DE SERVICIOS GENERALES', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '210', '_key' => '', 'name' => 'DIRECCIÓN GENERAL DE ARCHIVOS', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '386', '_key' => '', 'name' => 'DIRECCIÓN GENERAL DE BIBLIOTECAS', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '122', '_key' => '', 'name' => 'DIRECCIÓN GENERAL DE CÓMPUTO Y TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIÓN', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '807', '_key' => '', 'name' => 'DIRECCIÓN GENERAL DE CONTROL PATRIMONIAL', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '124', '_key' => '', 'name' => 'DIRECCIÓN GENERAL DE DESARROLLO INSTITUCIONAL', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '319', '_key' => '', 'name' => 'DIRECCIÓN GENERAL DE EDUCACIÓN CONTINUA', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '509', '_key' => '', 'name' => 'DIRECCIÓN GENERAL DE INTERNACIONALIZACIÓN', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '218', '_key' => '', 'name' => 'DIRECCIÓN INSTITUCIONAL DE IGUALDAD DE GÉNERO', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '224', '_key' => '', 'name' => 'ESCUELA DE FORMACIÓN DOCENTE Y DESARROLLO ACADÉMICO', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '221', '_key' => '', 'name' => 'ESTACIÓN DE SERVICIOS UNIGAS', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '222', '_key' => '', 'name' => 'FARMACIAS UNIVERSITARIAS ALEXANDER FLEMING', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '134', '_key' => '', 'name' => 'FUNDACIÓN UNIVERSITARIA', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '406', '_key' => '', 'name' => 'HOSPITAL UNIVERSITARIO', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '413', '_key' => '', 'name' => 'JARDÍN BOTÁNICO UNIVERSITARIO', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '126', '_key' => '', 'name' => 'RADIO BUAP', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '101', '_key' => '', 'name' => 'RECTORÍA', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '509', '_key' => '', 'name' => 'REVISTA ELEMENTOS', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '801', '_key' => '', 'name' => 'SECRETARIA ADMINISTRATIVA', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '201', '_key' => '', 'name' => 'SECRETARÍA GENERAL', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '118', '_key' => '', 'name' => 'SECRETARÍA TÉCNICA DEL H. CONSEJO UNIVERSITARIO', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '113', '_key' => '', 'name' => 'TESORERÍA GENERAL', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '117', '_key' => '', 'name' => 'UNIDAD DE TRANSPARENCIA, ACCESO A LA INFORMACIÓN Y PROTECCIÓN DE DATOS PERSONALES', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '141', '_key' => '', 'name' => 'UNIVERSIDAD PARA ADULTOS', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '301', '_key' => '', 'name' => 'VICERRECTORÍA DE DOCENCIA', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '501', '_key' => '', 'name' => 'VICERRECTORÍA DE EXTENSIÓN Y DIFUSIÓN DE LA CULTURA', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '401', '_key' => '', 'name' => 'VICERRECTORÍA DE INVESTIGACIÓN Y ESTUDIOS DE POSGRADO', 'type' => 'administrative', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '900', '_key' => '', 'name' => 'SEAES', 'type' => 'aux', 'created_at' => $now, 'updated_at' => $now],
            ['key' => '999', '_key' => '', 'name' => 'SIN UNIDAD ACADÉMICA', 'type' => 'aux', 'created_at' => $now, 'updated_at' => $now],
        ]);
    }
}
